language: python
notifications:
  email: false
env:
  global:
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install git+https://github.com/chfw/pyexcel-io.git  
  - pip install git+https://github.com/chfw/pyexcel.git
  - pip install git+https://github.com/chfw/pyexcel-webio.git
  - pip install git+https://github.com/chfw/pyexcel-xls.git
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install pyexcel-ods; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install pyexcel-ods; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then pip install git+https://github.com/chfw/ezodf.git; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then pip install git+https://github.com/chfw/ezodf.git; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then pip install pyexcel-ods3; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then pip install pyexcel-ods3; fi
script:
  make test
after_success:
  coveralls
