sudo: false
language: python
notifications:
  email: false
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.9
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION=2.0.1
    - python: 3.3
      env: DJANGO_VERSION=1.11.9
    - python: 3.4
      env: DJANGO_VERSION=1.6.11
    - python: 3.5
      env: DJANGO_VERSION=1.6.11
    - python: 3.3
      env: DJANGO_VERSION=1.9.13
    - python: 3.3
      env: DJANGO_VERSION=1.10.8
    - python: 3.5
      env: DJANGO_VERSION=1.7.11
    - python: 3.5
      env: DJANGO_VERSION=1.8.18
    - python: 3.6
      env: DJANGO_VERSION=1.6.11
    - python: 3.6
      env: DJANGO_VERSION=1.9.13
    - python: 3.6
      env: DJANGO_VERSION=1.10.8
    - python: 3.6
      env: DJANGO_VERSION=1.7.11
    - python: 3.6
      env: DJANGO_VERSION=1.8.18
before_install:
  - pip install Django==$DJANGO_VERSION
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt || pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
