sudo: false
language: python
notifications:
  email: false
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.2
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
matrix:
  exclude:
    - python: 2.6
      env: DJANGO_VERSION=1.7.11
    - python: 2.6
      env: DJANGO_VERSION=1.8.18
    - python: 2.6
      env: DJANGO_VERSION=1.9.13
    - python: 2.6
      env: DJANGO_VERSION=1.10.7
    - python: 2.6
      env: DJANGO_VERSION=1.11.2
    - python: 3.3
      env: DJANGO_VERSION=1.11.2
    - python: 3.4
      env: DJANGO_VERSION=1.6.11
    - python: 3.5
      env: DJANGO_VERSION=1.6.11
    - python: 3.3
      env: DJANGO_VERSION=1.9.13
    - python: 3.3
      env: DJANGO_VERSION=1.10.7
    - python: 3.5
      env: DJANGO_VERSION=1.7.11
    - python: 3.5
      env: DJANGO_VERSION=1.8.18
    - python: 3.6
      env: DJANGO_VERSION=1.6.11
    - python: 3.6
      env: DJANGO_VERSION=1.9.13
    - python: 3.6
      env: DJANGO_VERSION=1.10.7
    - python: 3.6
      env: DJANGO_VERSION=1.7.11
    - python: 3.6
      env: DJANGO_VERSION=1.8.18
before_install:
  - cd $HOME
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then deactivate && wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-5.7.1-linux_x86_64-portable.tar.bz2 -O - | tar -jxf - && echo 'Setting up aliases...' && ln -s pypy-5.7.1-linux_x86_64-portable pypy2-latest && export PATH=$HOME/pypy2-latest/bin/:$PATH && virtualenv --no-site-packages --python ~/pypy2-latest/bin/pypy pypy2-env && echo 'Creating custom env...' && source pypy2-env/bin/activate && python -V; fi"
  - cd -
  - pip install Django==$DJANGO_VERSION
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install flake8==2.6.2; fi
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt || pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
